#!/bin/bash
# This is a simple version of the fabric file provided that can be used to
# build the system.


# Configuration.
PROFILE_NAME="d8test"
PROFILE_ROOT="web/profiles/${PROFILE_NAME}"
REPOSITORY_ROOT_DIR=$(pwd)
GITHUB_ACCOUNT=anrizal

#Remove web directory before drush make
if [ -d "web" ]; then
  echo "chmod +w web/sites/default"
  chmod +w -R web/sites/default
  echo "Remove web directory before drush make"
  rm -rf web
fi

# Make Drupal core.
echo "==> Make Drupal core..."
drush make --working-copy platform.make web

# gitclone profile from github, adjust this
# https clone
git clone -b master https://github.com/${GITHUB_ACCOUNT}/${PROFILE_NAME}-profile.git web/profiles/${PROFILE_NAME}
# ssh clone
#git clone -b master git@github.com:${GITHUB_ACCOUNT}/${PROFILE_NAME}-profile.git web/profiles/${PROFILE_NAME}

# Make profile.
echo "==> Make profile..."
cd ${PROFILE_ROOT}
drush -y make --no-core ${PROFILE_NAME}.make --contrib-destination=.

# Get back to root directory.
cd ${REPOSITORY_ROOT_DIR}

echo "==> Build done!"

# Loop through and run scripts sent in as arguments.
for i in $*
  do
  if [ build-assets/$i ]; then
    echo "==> Run script: ${i}..."
      ./build-assets/$i
    fi
done
